### ISSUE TITLE
Support turbo mode

### ISSUE THREAD

**Issue by nebrelbug** [sdorra/content-collections#158]
When I run `next dev --turbo` it seems like Content Collections doesn't start running in the background.

Thanks for the great project!

**Comment by sdorra** [comment]
The last version of the next adapter has support for turbopack. Which version do you use?

**Comment by sdorra** [comment]
Should be fixed with [PR #1](https://github.com/nebrelbug/bengubler.com/pull/1). If it does not work, please feel free to reopen the issue.

**Comment by nebrelbug** [comment]
@sdorra that does indeed work! Thanks for the PR.

Side note, I figured out how to render MDX into HTML for my RSS feed. I'll probably write a blog post about it at some point soon!
