### ISSUE TITLE
docs: Use a documentation framework for docs

### ISSUE THREAD

**Issue by fuma-nama** [sdorra/content-collections#180]
Just noticed Content Collections on GitHub, thanks for the nice library!

## The Problem

The current docs of Content Collection doesn't support search, and I think it can look better with a docs framework.

I understand some maintainers may prefer a simple docs implementation, so please tell me if you have any opinions about the docs. 

## The Solution

I want to migrate the docs to Fumadocs, and is willing to submit a PR:

- Fumadocs supports Content Collections
- It is very flexible, and is dedicated on Next.js (which the docs is using now)

## Alternatives

Other docs frameworks like Nextra and Vitepress may also be a good option.

**Comment by sdorra** [comment]
> I understand some maintainers may prefer a simple docs implementation, so please tell me if you have any opinions about the docs.

I originally wanted to implement a search with [MiniSearch](https://github.com/lucaong/minisearch) as I've done on my [blog](https://sdorra.dev/), but I also have no problem using a framework. I have no experience with Fumadocs, but I would be happy to accept a PR if it fits into the design.
