### ISSUE TITLE
Table of content support

### ISSUE THREAD

**Issue by andthezhang** [sdorra/content-collections#199]
content-collections is awesome!

I would like to request a table of content implementation. Similar implementation based on content layer could be found at 

https://github.com/timlrx/pliny/blob/main/packages/pliny/src/ui/TOCInline.tsx

https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/209a9472068099d29ca5783063c5d421a1953436/app/blog/%5B...slug%5D/page.tsx#L116

```
<MDXLayoutRenderer
          code={}
          components={}
          toc={post.toc}
        />
```
Thanks!

**Comment by sdorra** [comment]
Thank you for your willingness to contribute. However, I believe the Table of Contents (TOC) feature is outside the scope of Content Collections. This functionality would be more appropriate in a separate MDX component or in a Remark plugin. While I appreciate your suggestion, I would like to keep the project's scope focused and manageable.

**Comment by piotrkulpinski** [comment]
> I think I got things working. Happy to contribute.
> 
> Currently I am doing it as a separate component.
> 
> ```
> <div>
>   <MDXContent code={mdx} components={mdxComponents} />
>   <TableOfContents toc={toc} />
> </div>
> ```
> 
> I feel like this is easier to manage vs adding it as a prop like `<MDXContent code={mdx} components={mdxComponents} toc={toc}/>`
> 
> Happy to contribute. I am considering
> 
> 1. Contribute to a blog with toc example in document
> 2. Contribute my current code to nextjs sample
> 
> lmk!

Could you share how you've implemented TOC using `content collections`? 

Thanks
