### ISSUE TITLE
Added content-collections with help of the documentation, but it is not working

### ISSUE THREAD

**Issue by i-am-henri** [sdorra/content-collections#215]
I stumbled accross this cool project today, and I wanted to integrate it into my portfolio, but it is sadly not working. I used your documentation for nextjs, and the code is avaiable [here](https://github.com/i-am-henri/henri/tree/dev). I added the package, the config and the folder, but it is still not working. I apprecciate every help ❤️

**Comment by sdorra** [comment]
I've checked your repository and it works fine for me.

```jsx
<ul>
  {allPosts.map((post) => (
    <li key={post._meta.fileName}>
      {post.title}
     </li>
   ))}
</ul>
```

I've added the snippet above to `./src/app/page.tsx` and the posts are listed on the start page.

**Comment by i-am-henri** [comment]
Thanks for your answer. Which os are you using? On a simular repo, there was an error that windows isn't working

**Comment by i-am-henri** [comment]
So, It is still not working for me, I removed the package and installed it again.  
![image](https://github.com/user-attachments/assets/cfc63c0e-9347-431b-a1d0-8101dc843205)
But as you can see, the array is empty. I have no clue why. Is it maybe bacause I'm on windows or I'm using bun?

**Comment by sdorra** [comment]
I'm not exactly sure what the problem is, but I was able to reproduce it on windows. A simple trim before the yaml parsing fixed it.
The patch above resolves the issue, but it has not been released yet. I will conduct more tests and release it if it works.

**Comment by sdorra** [comment]
I start the release. After release i will do one more test and then come back to you.

**Comment by sdorra** [comment]
@i-am-henri the version `0.6.3` of `@content-collections/core` should fix the problem.

**Comment by i-am-henri** [comment]
So, I've tried it now, and all is working. Thank you so much for this fix.

**Comment by i-am-henri** [comment]
So, I have another question. Does your library support hot reload at the time? Because, everytime when I hit save, I have to restart the entire server, that's very time consuming.

**Comment by i-am-henri** [comment]
But it logs in the console "start watching". I don't really understand this problem, It's maybe because windows?

**Comment by sdorra** [comment]
Could you create a new issue for the watch on Windows? I will have a look in the next few days.
