### ISSUE TITLE
Previous and next document

### ISSUE THREAD

**Issue by Kuzry** [sdorra/content-collections#245]
I'm wondering how best to add information about the previous and next post. I wanted to do it in the transform() function, but TypeScript throws errors when I try to return any retrieved document.

I have this code:
```typescript
transform: async (document, context) => {
    const mdx = await compileMDX(context, document);

    const previous = context.documents(docs).find(() => {
      // find previous
      return true;
    });

    return {
      ...document,
      mdx,
      previous,
    };
},
```

The error is: transform implicitly has return type any because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

I'm not sure if it's a good idea to do this in the transform() function. Any ideas on how to do it properly to add information about the previous and next post?

**Comment by sdorra** [comment]
Hi @Kuzry it is not possible to access the documents of a collection with in the transform function of the same collection.

The simplest thing which comes to my mind to implement previous/next is to do this in you application code. First you have to [sort your collection](https://www.content-collections.dev/docs/sorting), the you can search the index of the current document and calculate the next and the previous doc.

```ts
const index = sortedDocs.findIndex((doc) =>  doc._meta.path === currentDoc._meta.path);
const previous = sortedDocs[index - 1];
const next =  sortedDocs[index + 1];
```
