### ISSUE TITLE
[Bug] @content-collections/mdx - Line breaks do not get created

### ISSUE THREAD

**Issue by nwparker** [sdorra/content-collections#250]
When using `@content-collections/mdx`

`content-collections.ts`:
```
import { defineCollection, defineConfig } from '@content-collections/core';
import { compileMDX } from '@content-collections/mdx';

const posts = defineCollection({
  name: 'posts',
  directory: 'src/posts',
  include: '*.mdx',
  schema: (z) => ({
    title: z.string().min(1),
  }),
  transform: async (document, context) => {
    const mdx = await compileMDX(context, document);
    return {
      ...document,
      mdx,
    };
  },
});

export default defineConfig({
  collections: [posts],
});
```

Example `.mdx`:
```
---
title: 'Test 123'
---

Line one





Should be a line break:






Last line
```

Code is being rendered with:
`<MDXContent code={post.mdx} />`

Instead of containing line breaks between p tags, the resulting HTML will be:
```
<p>Line one</p>
<p>Should be a line break:</p>
<p>Last line</p><
```

_Side note: I also tested [remark-breaks](https://github.com/remarkjs/remark-breaks) but it does not appear to resolve or have any effect on this issue_

**Comment by nwparker** [comment]
Hi @sdorra ,

Thank for your elaborating!

For remark-breaks, I used it this way:
```
import { defineCollection, defineConfig } from '@content-collections/core';
import { compileMDX } from '@content-collections/mdx';
import remarkBreaks from 'remark-breaks';

const posts = defineCollection({
  name: 'posts',
  directory: 'src/posts',
  include: '*.mdx',
  schema: (z) => ({
    title: z.string().min(1),
  }),
  transform: async (document, context) => {
    const mdx = await compileMDX(context, document, { remarkPlugins: [remarkBreaks] });
    return {
      ...document,
      mdx,
    };
  },
});

export default defineConfig({
  collections: [posts],
});

```

**Comment by sdorra** [comment]
Ok, I can confirm that it does not work. It looks like neither the markdown nor the mdx packages renders the breaks. I'm not sure why, but I will do some research in the next week.

**Comment by sdorra** [comment]
Sorry, but I misunderstood remark-breaks. It works as intended, even within content collections. It allows line breaks within a paragraph. Line breaks between the breaks are removed, as described in the Markdown specification.

```md
Line
Break
```

Will render with remark-breaks:

```md
<p>Line<br />Break</p>
```

Please have a look at https://github.com/remarkjs/remark-breaks/issues/2

**Comment by sdorra** [comment]
If you only want to add spacing and you are using MDX, consider adding a React component that allows you to add the extra spacing.

**Comment by nwparker** [comment]
Thanks for all the details and research here @sdorra , that makes sense!

Feel free to close the ticket (I'll leave this up to you)
