### ISSUE TITLE
Access File Metadata

### ISSUE THREAD

**Issue by Flowlicious** [sdorra/content-collections#276]
It would be nice if we could access the file metadata and use it in the schema for example creation or modified date.

**Comment by sdorra** [comment]
This can easily be done with the transform function. Here us an example which uses git to get the last modified date from the repository:

https://www.content-collections.dev/docs/transform#get-last-modification-date-from-git

You could also use the filesystem api to get the last modification time.

I will post an example at the beginning of next week.

**Comment by sdorra** [comment]
Here is the sample:

```ts
import { defineCollection, defineConfig } from "@content-collections/core";
import path from "node:path";
import fs from "node:fs/promises";

const posts = defineCollection({
  name: "posts",
  directory: "content/posts",
  include: "**/*.md",
  schema: (z) => ({
    title: z.string(),
    summary: z.string(),
  }),
  transform: async (post, { collection }) => {
    const filePath = path.join(collection.directory, post._meta.filePath);
    const { mtimeMs, birthtimeMs } = await fs.stat(filePath);
    return {
      ...post,
      createdAt: new Date(birthtimeMs),
      updatedAt: new Date(mtimeMs),
    };
  },
});

export default defineConfig({
  collections: [posts],
});
```

If this is not what you are searching for, feel free to reopen the issue.
