### ISSUE TITLE
Improve serialization

### ISSUE THREAD

**Issue by sdorra** [sdorra/content-collections#29]
At the time of writing, content-collections serialize the generated documents as JSON. The problem with this approach is that JSON has a limited set of data types (string, number, boolean, null, object, or array), and this is why the generated documents have only those data types as well (#21).

It would be nice if data types such as `Date` could be used as part of the document as well. We could possibly achieve this by using a library such as [serialize-javascript](https://github.com/yahoo/serialize-javascript) instead of `JSON.stringify`.

**Comment by mustaqimarifin** [comment]
would `structuredClone()` work?

**Comment by sdorra** [comment]
I'm not sure what you mean. Do you mean the use of `structuredClone()` instead of a switch to a another serialization method? Or if it work after the switch?
