### ISSUE TITLE
Wrong import of config in the generated dts

### ISSUE THREAD

**Issue by marcus-dc** [sdorra/content-collections#30]
First of all, I would like to thank you for this amazing library.

I've encountered an issue regarding the generated `.d.ts` file. It imports the configuration from the root directory (`content-collections.ts`) correctly. However, the path of the import uses backslashes (`\`) instead of forward slashes (`/`).
```js
import configuration from "..\..\content-collections.ts";
// instead of
import configuration from "../../content-collections.ts";
```
I'm currently using turborepo monorepo
* Win10 OS
* next 14.1.4 (in a workspace)
* turbo 1.13.0 (root)

**Comment by sdorra** [comment]
@marcus-dc Thanks for the report. The issue is fixed with the version v0.4.1 auf `@content-collections/core`.
