### ISSUE TITLE
Webpack warning during Next.js Build

### ISSUE THREAD

**Issue by wottpal** [sdorra/content-collections#309]
In one of my projects, I get the following warnings with `@content-collections/next` enabled during build (it's gone, if i deactivate it in my `next.config.js`):

```
$ next build
Starting content-collections ./content-collections/index.ts
build started ...
... finished build of 2 collections and 2 documents in 9ms
  ▲ Next.js 15.0.0-canary.157
  - Environments: .env.local
  - Experiments (use with caution):
    · ppr

   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /[...]/node_modules/bundle-require/dist/index.js for build dependencies failed at 'import(file)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
```

**Comment by sdorra** [comment]
I can't reproduce it, and next.js should not bundle the `bundle-require` package, at least not the dependency of content collections. Can you post your content collections config?

**Comment by wottpal** [comment]
Hey, I just invited you to a boilerplate repo of mine where the build warning is occurring. Just run:

```bash
# Install dependencies
bun install

# Create empty environment
cp .env.local.example .env.local

# Build
bun run build
```

**Comment by sdorra** [comment]
@wottpal could you please test the preview release of #318

**Comment by wottpal** [comment]
The warning is gone with #318! 🚀
