### ISSUE TITLE
Ability to render MDX with edge runtimes

### ISSUE THREAD

**Issue by lauri865** [sdorra/content-collections#331]
I'm loving the DX of content collections so far.

Is there any way recipe to getting MDX rendering in Cloudflare Workers to work?

`For security reasons, the Cloudflare Workers runtime does not allow dynamic code evaluation via eval() or new Function() . It also requires all modules to be defined ahead-of-time before execution starts.`

Hence `<MDXContent />` doesn't work, and I'm wondering if and what the alternatives are here, or whether we're locked to Vercel forever if we decide to invest further into adopting content-collections with Nextjs.

**Comment by lauri865** [comment]
After some research, it seems like [`safe-mdx` is the way to go](https://github.com/holocron-hq/safe-mdx) for now.

It has some limitations (no importing, etc). But maybe importing within mdx files is not so great anyways. I can only imagine if we want to move over to a headless CMS at some point that we would need to refactor so many things to make it work if we start importing components within MDX directly.

**Comment by sdorra** [comment]
@lauri865 could you please post you solution with mdx (`transform` function and client code)."Perhaps it makes sense to include an example or even a separate package for safe-mdx.

**Comment by savokiss** [comment]
Same problem, I don't know how to intergrate `safe-mdx`, seems I have to switch from MDX to markdown. 😢
