### ISSUE TITLE
Build Error - Cannot read properties of undefined (reading 'collections')

### ISSUE THREAD

**Issue by RanNahmany** [sdorra/content-collections#348]
hi all

I switched from windows to a macos
For a project that works on Windows, I get now an exception error in Mac when I'm trying to run **"npm run dev"** or **"pnpm dev"** in a nextjs project.
the error i get is:

**TypeError: Cannot read properties of undefined (reading 'collections')**
original module path - "node_modules/@content-collections/integrations/src/index.ts"

when i entered the "exception file" i saw that it is looking for "stats -> documents" and "stats -> collections" inside the **event** of the **"builder:end"**, which is not exists when i print it to console. only **"startedAt"** and **"endedAt"**:
<img width="887" alt="image" src="https://github.com/user-attachments/assets/51d5423c-2346-4d17-894e-e3821ed31e01">
<img width="780" alt="image" src="https://github.com/user-attachments/assets/4e1a0563-1235-424e-aeee-ffc0895109c7">

Can anyone help me with this one?
Thanks in advance!

the original error when i run "npm run dev" or "pnpm dev"
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/97c109d6-7d6d-4077-9290-909f43237464">

**Comment by sdorra** [comment]
This looks like a mismatch between `@content-collections/core` and `content-collections/integrations`. Can you try to upgrade `@content-collections/core`?

**Comment by RanNahmany** [comment]
> This looks like a mismatch between `@content-collections/core` and `content-collections/integrations`. Can you try to upgrade `@content-collections/core`?

**Solved it! Thank you @sdorra **
