### ISSUE TITLE
Command not found on `pnpm dev`

### ISSUE THREAD

**Issue by happer64bit** [sdorra/content-collections#38]
## Issue Description
I'm encountering issues with running the pnpm scripts in my project. Specifically, the `dev` script is failing to execute as expected.

## Details
- **Project Name:** website
- **Version:** 0.1.0

### Error Message
```
> 'content-collections' is not recognized as an internal or external command, operable program or batch file.
> 'watch'' is not recognized as an internal or external command, operable program or batch file.
> 'build-scripts' is not recognized as an internal or external command, operable program or batch file.
> 'dev'' is not recognized as an internal or external command, operable program or batch file.
```

## Expected Behavior
The `dev` script should start the development server and watch for changes.

## Actual Behavior
The `dev` script fails with the mentioned errors.

## Additional Information
- Operating System: Windows 11
- Node.js Version: `v20.11.1`
- pnpm Version: `8.15.4`
- framework: `next@14.1.4`

## `package.json`

```
{
  "name": "website",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "concurrently 'content-collections watch' 'next dev --turbo'",
    "build": "content-collections build && next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.1.4",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@content-collections/cli": "^0.1.2",
    "@content-collections/core": "^0.4.1",
    "@content-collections/next": "^0.1.3",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "concurrently": "^8.2.2",
    "eslint": "^8",
    "eslint-config-next": "14.1.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
```

**Comment by sdorra** [comment]
Ok, it looks like a problem with the cli on windows. Sadly i've no windows machine for testing at the moment. But you do not need the cli for next.js, there is a integration special for next.js: 

- https://www.content-collections.dev/docs/integrations/next

The integration will work with the normal `next dev` and `next build`, there is no need for `concurrently`.

**Comment by sdorra** [comment]
If anyone knows how to make a Node CLI app work on Windows, your help is welcome.

**Comment by sdorra** [comment]
@happer64bit after [Cloudogu](https://cloudogu.com) was kind enough to grant me access to a Windows VM for testing, i was able to reproduce the issue. The issue wasn't with the CLI but with how the dev script was defined. The example in the documentation uses single quotes, which is suitable for Linux/OSX but not for Windows. Using escaped double quotes resolves the problem.

```json
{
  "scripts": {
    "dev": "concurrently \"content-collections watch\" \"next dev --turbo\"",
    "build": "content-collections build && next build"
  }
}
```

I have now updated the sample in the documentation.
