### ISSUE TITLE
schema is only validation? can we account for coercion too? 

### ISSUE THREAD

**Issue by airtonix** [sdorra/content-collections#68]
It'd be nice to be able to use zod coercion to turn yaml ISO date strings into JS Date objects.

```ts
z.string().pipe(z.coerce.date())

z.string().transform((value) => new Date(value))

```

but these end up creating typeerrors: 

![image](https://github.com/sdorra/content-collections/assets/61225/4468ea05-4d8e-47e7-acde-0e20d8c17f6c)

**Comment by sdorra** [comment]
You can use `coerce` or `transform`, but the output must be a valid JSON object since content collections store documents as JSON files. There is an existing issue addressing the problem with the date (#29).
